#!/usr/bin/python3
##
## EPITECH PROJECT, 2025
## G-MAT-100-LYN-1-1-103cipher-14 [WSL: Ubuntu-24.04]
## File description:
## 103cipher
##
import sys
from matrix_op import encrypt, decrypt

def print_help():
    print("USAGE")
    print("    ./103cipher message key flag")
    print("DESCRIPTION")
    print("    message a message, made of ASCII characters")
    print("    key the encryption key, made of ASCII characters")
    print("    flag 0 for the message to be encrypted, 1 to be decrypted")

def main():
    if len(sys.argv) == 2 and sys.argv[1] == "-h":
        print_help()
        sys.exit(0)

    if len(sys.argv) != 4 or len(sys.argv[1]) <= 0 or len(sys.argv[2]) <= 0:
    # if len(sys.argv) != 4:
        sys.exit(84)

    try:
        message = sys.argv[1]
        key = sys.argv[2]
        flag = int(sys.argv[3])

        if flag != 0 and flag != 1:
            sys.exit(84)
        if flag == 0:
            encrypt(message, key)
        else:
            decrypt(message, key)

    except Exception as e:
        # print(e)
        sys.exit(84)

if __name__ == "__main__":
    main()