#!/bin/bash
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

BINARY="./103cipher"

test_cmd() {
    description=$1
    expected=$2
    cmd=$3

    eval "$cmd" > /dev/null
    ret=$?

    if [ $ret -eq $expected ]; then
        echo -e "[${GREEN}OK${NC}] $description"
    else
        echo -e "[${RED}KO${NC}] $description"
        echo -e "      Attendu: $expected, Reçu: $ret"
        echo -e "      Cmd: $cmd"
    fi
}

echo -e "${BLUE}=== TESTS CLASSIQUES (Sujet) ===${NC}"
test_cmd "Sujet Encryption (Homer S)" 0 "$BINARY \"Just because I don't care doesn't mean I don't understand.\" \"Homer S\" 0"
test_cmd "Sujet Decryption (Homer S)" 0 "$BINARY \"26690 21552 11810 19718 16524 13668 25322 22497 14177 28422 26097 16433 12333 11874 5824 27541 23754 14452 17180 17553 7963 26387 22047 13895 18804 14859 12033 27738 23835 15331 21487 16656 13238 21696 15978 6976 20750 23307 14093 16788 11751 8981 22339 24861 15619 21295 16524 13668 26403 23610 15190 29451 25764 16106 26394 23307 14093 3312 5106 5014\" \"Homer S\" 1"

echo -e "\n${BLUE}=== TESTS DE ROBUSTESSE (Tailles de Matrices) ===${NC}"
test_cmd "Matrice 1x1 (Key='A')" 0 "$BINARY \"A\" \"A\" 0"

test_cmd "Matrice 2x2 avec Padding (Key='ab')" 0 "$BINARY \"Message\" \"ab\" 0"

test_cmd "Matrice 3x3 avec Padding (Key='abcde')" 0 "$BINARY \"Test\" \"abcde\" 0"

echo -e "\n${BLUE}=== TESTS LOGIQUES (Inversion impossible) ===${NC}"
test_cmd "Matrice Singulière (Non-inversible) -> Exit 84" 84 "$BINARY \"NimporteQuoi\" \"aa\" 1"

echo -e "\n${BLUE}=== TESTS D'ERREURS (Inputs Invalides) ===${NC}"
test_cmd "Pas d'arguments" 84 "$BINARY"
test_cmd "Clé vide" 84 "$BINARY \"Message\" \"\" 0"
test_cmd "Message vide" 84 "$BINARY \"\" \"Key\" 0"
test_cmd "Flag invalide (3)" 84 "$BINARY \"Msg\" \"Key\" 3"
test_cmd "Flag invalide (Lettre)" 84 "$BINARY \"Msg\" \"Key\" f"